version: '3.8'

services:
  db:
    image: postgres:18.1-alpine
    container_name: scandomen_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
    expose:
      - 6379
    restart: always
    hostname: redis
    container_name: redis
    volumes:
      - ../BAS/redis:/data

  celery_worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A app.worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - db

volumes:
  postgres_data: