"""refactor_models_indexes_and_types

Revision ID: 701a3e70bdac
Revises: 9b636ef9ec09
Create Date: 2026-04-11 16:55:03.204322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '701a3e70bdac'
down_revision: Union[str, Sequence[str], None] = '9b636ef9ec09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_id'), table_name='domains')
    op.create_index(op.f('ix_domains_target_id'), 'domains', ['target_id'], unique=False)
    op.create_unique_constraint(None, 'domains', ['domain_name'])
    op.alter_column('ports', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ports', 'service_version',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ports', 'banner',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.create_index(op.f('ix_ports_domain_id'), 'ports', ['domain_id'], unique=False)
    op.create_index(op.f('ix_ports_port_number'), 'ports', ['port_number'], unique=False)
    op.alter_column('ssl_certificates', 'not_before',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ssl_certificates', 'not_after',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('ssl_certificates', 'public_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=800),
               existing_nullable=False)
    op.create_unique_constraint('uq_serial_issuer', 'ssl_certificates', ['serial_number', 'issuer'])
    op.drop_index(op.f('ix_targets_id'), table_name='targets')
    op.create_unique_constraint(None, 'targets', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='unique')
    op.create_index(op.f('ix_targets_id'), 'targets', ['id'], unique=False)
    op.drop_constraint('uq_serial_issuer', 'ssl_certificates', type_='unique')
    op.alter_column('ssl_certificates', 'public_key',
               existing_type=sa.String(length=800),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('ssl_certificates', 'not_after',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('ssl_certificates', 'not_before',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ports_port_number'), table_name='ports')
    op.drop_index(op.f('ix_ports_domain_id'), table_name='ports')
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.alter_column('ports', 'banner',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('ports', 'service_version',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ports', 'service_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'domains', type_='unique')
    op.drop_index(op.f('ix_domains_target_id'), table_name='domains')
    op.create_index(op.f('ix_domains_id'), 'domains', ['id'], unique=False)
    # ### end Alembic commands ###
