"""refactor_to_ip_centric_schema

Revision ID: 85b7580379f7
Revises: 701a3e70bdac
Create Date: 2026-04-26 19:04:57.469131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85b7580379f7'
down_revision: Union[str, Sequence[str], None] = '701a3e70bdac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_domain_id'), 'ip_addresses', ['domain_id'], unique=False)
    op.create_index(op.f('ix_ip_addresses_ip'), 'ip_addresses', ['ip'], unique=False)
    op.drop_table('domain_ssl_link')
    op.drop_column('domains', 'ip_address_v6')
    op.drop_column('domains', 'ip_address_v4')
    op.add_column('ports', sa.Column('ip_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_ports_domain_id'), table_name='ports')
    op.create_index(op.f('ix_ports_ip_id'), 'ports', ['ip_id'], unique=False)
    op.drop_constraint(op.f('ports_domain_id_fkey'), 'ports', type_='foreignkey')
    op.create_foreign_key(None, 'ports', 'ip_addresses', ['ip_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ports', 'domain_id')
    op.add_column('ssl_certificates', sa.Column('ip_id', sa.Integer(), nullable=False))
    op.add_column('ssl_certificates', sa.Column('subdomains', sa.JSON(), nullable=False))
    op.alter_column('ssl_certificates', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ssl_certificates', 'issuer',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ssl_certificates', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ssl_certificates', 'not_before',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('ssl_certificates', 'not_after',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('ssl_certificates', 'public_key',
               existing_type=sa.VARCHAR(length=800),
               nullable=True)
    op.drop_constraint(op.f('uq_serial_issuer'), 'ssl_certificates', type_='unique')
    op.create_index(op.f('ix_ssl_certificates_ip_id'), 'ssl_certificates', ['ip_id'], unique=True)
    op.create_foreign_key(None, 'ssl_certificates', 'ip_addresses', ['ip_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ssl_certificates', type_='foreignkey')
    op.drop_index(op.f('ix_ssl_certificates_ip_id'), table_name='ssl_certificates')
    op.create_unique_constraint(op.f('uq_serial_issuer'), 'ssl_certificates', ['serial_number', 'issuer'], postgresql_nulls_not_distinct=False)
    op.alter_column('ssl_certificates', 'public_key',
               existing_type=sa.VARCHAR(length=800),
               nullable=False)
    op.alter_column('ssl_certificates', 'not_after',
               existing_type=sa.String(length=100),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ssl_certificates', 'not_before',
               existing_type=sa.String(length=100),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('ssl_certificates', 'subject',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ssl_certificates', 'issuer',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ssl_certificates', 'serial_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('ssl_certificates', 'subdomains')
    op.drop_column('ssl_certificates', 'ip_id')
    op.add_column('ports', sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ports', type_='foreignkey')
    op.create_foreign_key(op.f('ports_domain_id_fkey'), 'ports', 'domains', ['domain_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ports_ip_id'), table_name='ports')
    op.create_index(op.f('ix_ports_domain_id'), 'ports', ['domain_id'], unique=False)
    op.drop_column('ports', 'ip_id')
    op.add_column('domains', sa.Column('ip_address_v4', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('ip_address_v6', sa.VARCHAR(length=39), autoincrement=False, nullable=True))
    op.create_table('domain_ssl_link',
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certificate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['ssl_certificates.id'], name=op.f('domain_ssl_link_certificate_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], name=op.f('domain_ssl_link_domain_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'certificate_id', name=op.f('domain_ssl_link_pkey'))
    )
    op.drop_index(op.f('ix_ip_addresses_ip'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_domain_id'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    # ### end Alembic commands ###
